plot.py
=> close issue #16

field.py, limits.py, menu.py, plot.py, tilt.py, tools.py, version
Moved the mouse click-value interface to tools.
Created ValueClick class for this interface.
Cleaned up ZoomPan class.
Fixed bug in limits Dialog that resulted in re-plot when cancel was selected.  Now only redraws plots when "OK" is clicked.
=> Enabled tools.py interface.

plot.py, tools.py
=> Added selectable region of interest.

artview/components/__init__.py, artview/components/menu.py, artview/components/plot.py, artview/components/tools.py, artview/core/__init__.py, artview/core/common.py, artview/core/variable_choose.py, artview/plugins/calculate_attenuation.py, artview/plugins/dealias_region_based.py, artview/plugins/dealias_unwrap_phase.py, artview/plugins/exemple1.py, artview/plugins/phase_proc_lp.py, artview/scripts/standard.py, setup.py
This is a big restructuration, may be you should merge it into a separated branch to have to opportunity to give it a good look before accepting. I took opportunity and turn artview into a package and add documentation.
* You can do both: `import artview` and start components directly, or run `python artview -d ... -f ...` in the command line and have it starting in the standard way. Our previous **execute_two.py** is now in **artview/scripts/standard.py**
* There is also a `setup.py`, please revise that to make sure you agree with all points. I've used pyart's `setup.py` as a model, may be we should verify if Jonathan has any objection to that.
* I set up sphinx to build the documentation, give a look into `doc/build/html/index.html`. It still need like a lot of correction, but we have …
=> Issues 29 and 31

artview/components/plot_radar.py, artview/components/tools.py
=> BUG: reset default update for new scan type

artview/components/__init__.py, artview/components/plot_radar.py, artview/components/roi.py, artview/components/tools.py, artview/core/variable_choose.py, artview/scripts/map_to_grid.py, artview/scripts/standard.py
This is a suggestion for a change in ROI and I want to emphasize as a suggestion this can also be rejected, I can also see reasons for that. This is mostly personal preference and a sense of what is better that I can't really explain, there is however one positive point, the new ROI is independent of Vradar and therefore can be used (in the future) with grid.
The new ROI may be found in the components menu in the menubar. But this is open to discussion.
Take your time with this, this is NOT a priority and I pretend to focus more in the documentation
=> Roi component

README.md, artview/components/__init__.py, artview/components/component_control.py, artview/components/menu.py, artview/components/pick_value.py, artview/components/plot_grid.py, artview/components/plot_radar.py, artview/components/roi.py, artview/components/select_region.py, artview/components/tools.py, artview/core/common.py, artview/core/points.py, artview/scripts/map_to_grid.py, artview/scripts/standard.py
Added column headers to ROI saved CSV files.
Update open ROI saved files.
Enhanced error checking in ROI.
Added ROI stats output.
Fix LongMessage modeless to display.
Fixed a minor bug for Python 2.6
Added a tool reset button.
Updated infolabel.
=> ROI and infolabel update.

artview/components/__init__.py, artview/components/plot_radar.py, artview/components/plot_simple.py, artview/components/select_region.py
Added a simplified display, PlotDisplay, for basic plotting.
Added histogram plotting to SelectRegion.
Minor code cleanup.
=> Simple plot class, histogram for SelectRegion.

artview/components/tools.py, artview/parser.py
I couldn’t get the program to compile under my Python 3. I traced the
issue to minor problems in components/tools.py and parser.py, which I
have fixed.
Also pep8'ed tools.py.
=> Minor edits for Python 3

artview/components/plot_grid.py, artview/components/plot_radar.py, artview/components/plot_simple.py, artview/components/select_region.py, artview/components/tools.py
Solve bug reported in issue #80
=> BUG: force matplotlib to use PyQt4 as backend

artview/core/core.py, artview/plugins/console.py
Add a plugin to give the user direct access to artview, so he can change the data directly in python. It is a powerful tool for some one that knows what he is doing, but it can be dangerous as well if not used carefully. There may be some ways of making it safer, but it involves much more code for emulating a terminal, however the idea itself of giving a terminal to someone is risk.
=> Terminal Access

README.md, artview/components/__init__.py, artview/components/level.py, artview/components/menu.py, artview/components/plot_grid.py, artview/components/plot_grid_legacy.py, artview/components/plot_radar.py, artview/components/tools.py, artview/plugins/io.py, artview/scripts/_common.py, artview/scripts/standard.py, setup.py
Updates to address issues #110, #108, #96 and test for dependencies in `setup.py` (#109)
=> Minor Updates

artview/components/nav.py, artview/modes.py
Af first I thought it would be just a simple correction, for instance adding NewFilelist to the SharedVariables dict. But I notice there were several small things that needed correction. I will make comments and hope you can figure out were it got it wrong.
=> correct handel of Vfilelist

artview/components/menu.py, artview/core/common.py, artview/plugins/dealias_region_based.py, artview/plugins/dealias_unwrap_phase.py, artview/plugins/manual_filter.py, artview/plugins/manual_unfold.py, artview/plugins/phase_proc_lp.py
=> BUG: issues #146 and #147

artview/components/tools.py
bug discovered in issue #148 (but not the issue itself)
=> BUG: zoom outside picture

artview/plugins/radar_collection.py
just to make sure the master is working in python3
=> BUG: python3

artview/components/plot_radar.py, artview/core/core.py
Added Shared variable to allow the user to select whether to ignore edge gates, by passing the edges keyword.
=> ENH: Add Graphical Edges keyword to plots.

artview/components/limits.py, artview/components/plot_grid.py, artview/components/plot_radar.py, artview/core/core.py, artview/modes.py, artview/plugins/background.py
issue #114.
This is not a 100% user friendly function to add a map to display, but rather it shows the option. As we depend on data that we do not have, I would not develop this further unless someone really needs.
=> Topography Map

artview/components/limits.py, artview/components/plot_grid.py, artview/components/plot_radar.py, artview/core/core.py, artview/modes.py, artview/plugins/background.py
as the other PR turned into a discussion and I don't want to interrupt it, I'm resubmiting it.
This includes a image background and a warning before loading the topography from the internet.
=> Topography Map 2

artview/components/display.py, artview/components/image_text.py, artview/components/limits.py, artview/components/pick_value.py, artview/components/plot_grid.py, artview/components/plot_grid_legacy.py, artview/components/plot_radar.py, artview/components/plot_simple.py, artview/components/toolbox.py
This first PR is for comments. This was a little more difficult than I imagined, requiring sending the display to the new `ImageTextBox` tool and housekeeping was a bit of a bear to sort out.
Once we work out the details, I'll build this into `plot_grid` as well. That should be reasonably simple.
=> ENH: Add Image Text. Modify path links for tools.

artview/components/__init__.py, artview/components/correlation.py, artview/components/menu.py, artview/components/plot_radar.py, artview/modes.py, artview/scripts/_common.py
show simple correlation graphic. It could use some expansion, including a recession line.
=> add correlation

artview/view.py
In preparation to the mini course I had to add this correction for consecutive running of artview
=> changes for mini course

setup.py
Merging this modified setup.py for v1.3 release.
=> Release branch v1.3
